version: '3.8'

services:
  frontend:
    build: ./frontend
    expose:
      - "80"
    environment:
      - VITE_API_URL=http://nginx:80
    networks:
      - bb-chat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build: ./backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://nginx:80
    networks:
      - bb-chat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build: ./nginx
    ports:
      - "8888:80"
      - "8443:443"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy    
    networks:
      - bb-chat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bb-chat-network:
    driver: bridge
